<?php

/**
 * @copyright EveryWorkflow. All rights reserved.
 *
 * @var \EveryWorkflow\Connector\Block\Adminhtml\MageAdmin $block
 */
?>

<link rel="stylesheet" href="<?= $block->getConfigHelper()->getMageAdminConfig('mage_admin_css_href') ?>">
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="EveryWorkflow_MageAdmin_Init" style="min-height: 80vh"></div>
<script src="<?= $block->getConfigHelper()->getMageAdminConfig('mage_admin_js_runtime_src') ?>" defer></script>
<script src="<?= $block->getConfigHelper()->getMageAdminConfig('mage_admin_js_src') ?>" defer></script>
